# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VirtualSolutionCodingChallenge' do
  pod 'AFNetworking'
  pod 'JSONModel'
  pod 'SDWebImage'
  use_frameworks!

  # Pods for VirtualSolutionCodingChallenge

  target 'VirtualSolutionCodingChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VirtualSolutionCodingChallengeUITests' do
    # Pods for testing
  end

end
